// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUCLMf77QqQEKSDsliYj-Pzhfy5XtvOnU',
    appId: '1:1085770219243:web:ef354f09a8f52f64bcc8ae',
    messagingSenderId: '1085770219243',
    projectId: 'act7-android-71f8f',
    authDomain: 'act7-android-71f8f.firebaseapp.com',
    storageBucket: 'act7-android-71f8f.firebasestorage.app',
    measurementId: 'G-PWN2B6D79J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS4nOt3mvlcGZAG7FxFncbrgqIUhwVDbM',
    appId: '1:1085770219243:android:a81724f35a77b590bcc8ae',
    messagingSenderId: '1085770219243',
    projectId: 'act7-android-71f8f',
    storageBucket: 'act7-android-71f8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq7Zl8wNJ_nntmdMJk0aisw_XrD6hltL0',
    appId: '1:1085770219243:ios:e696f0635acbf949bcc8ae',
    messagingSenderId: '1085770219243',
    projectId: 'act7-android-71f8f',
    storageBucket: 'act7-android-71f8f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq7Zl8wNJ_nntmdMJk0aisw_XrD6hltL0',
    appId: '1:1085770219243:ios:e696f0635acbf949bcc8ae',
    messagingSenderId: '1085770219243',
    projectId: 'act7-android-71f8f',
    storageBucket: 'act7-android-71f8f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
